### ISSUE TITLE
테스트 코드 수정

### ISSUE THREAD

**Issue by yumyeonghan** [back-og/back-log#131]
### 📄 Describe

- 테스트 코드 수정
    - 컨트롤러 테스트 검증 추가
    - 컨벤션에 맞게 테스트 코드 통일화

### ✅ Tasks

- [ ] 테스트 코드 수정
    - [ ] 컨트롤러 테스트 검증 추가
    - [ ] 컨벤션에 맞게 테스트 코드 통일화
